package Rendering.Text;

import java.awt.Color;
import java.awt.Font;

public class CashedTextImage
{

	String Text;
	Color Hue;
	Font Style;

	public CashedTextImage(String Text, Color Hue, Font Style)
	{
		this.Text = Text;
		this.Hue = Hue;
		this.Style = Style;
	}

	// Autogenerated by Eclipse
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((Hue == null) ? 0 : Hue.hashCode());
		result = prime * result + ((Style == null) ? 0 : Style.hashCode());
		result = prime * result + ((Text == null) ? 0 : Text.hashCode());
		return result;
	}

	// Autogenerated by Eclipse
	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CashedTextImage other = (CashedTextImage) obj;
		if (Hue == null)
		{
			if (other.Hue != null)
				return false;
		}
		else if (!Hue.equals(other.Hue))
			return false;
		if (Style == null)
		{
			if (other.Style != null)
				return false;
		}
		else if (!Style.equals(other.Style))
			return false;
		if (Text == null)
		{
			if (other.Text != null)
				return false;
		}
		else if (!Text.equals(other.Text))
			return false;
		return true;
	}

}